# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shakeitup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('date_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Album_By_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_genres', to='shakeitup.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('birth_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist_On_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_artists', to='shakeitup.Album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_artists', to='shakeitup.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('date_released', models.DateField(null=True)),
                ('song_length', models.DurationField(null=True)),
                ('danceability', models.DecimalField(decimal_places=10, max_digits=20)),
                ('collaborating_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist')),
                ('composing_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist')),
                ('featured_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist')),
                ('songwriter_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song_By_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='shakeitup.Genre')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='shakeitup.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Song_On_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='shakeitup.Album')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='shakeitup.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Song_On_Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='shakeitup.Playlist')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='shakeitup.Song')),
            ],
        ),
        migrations.AddField(
            model_name='album_by_genre',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_genres', to='shakeitup.Genre'),
        ),
    ]
