# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:49
from __future__ import unicode_literals
import os
from sys import path
from django.core.management import call_command
from django.db import migrations, models

def load_data(apps, schema_editor):
    call_command('loaddata', 'initial_data.json', app_label='shakeitup') 
    

def unload_data(apps, schema_editor):
    "Brutally deleting all entries for this model..."
    Album_By_Genre = apps.get_model("shakeitup", "Album_By_Genre")
    Album_By_Genre.objects.all().delete()
    Artist_On_Album = apps.get_model("shakeitup", "Artist_On_Album")
    Artist_On_Album.objects.all().delete()
    Song_By_Genre = apps.get_model("shakeitup", "Song_By_Genre")
    Song_By_Genre.objects.all().delete()
    Song_On_Album = apps.get_model("shakeitup", "Song_On_Album")
    Song_On_Album.objects.all().delete()
    Song_On_Playlist = apps.get_model("shakeitup", "Song_On_Playlist")
    Song_On_Playlist.objects.all().delete()
    Album = apps.get_model("shakeitup", "Album")
    Album.objects.all().delete()
    Song = apps.get_model("shakeitup", "Song")
    Song.objects.all().delete()
    Playlist = apps.get_model("shakeitup", "Playlist")
    Playlist.objects.all().delete()
    Artist = apps.get_model("shakeitup", "Artist")
    Artist.objects.all().delete()
    Genre = apps.get_model("shakeitup", "Genre")
    Genre.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0002_auto_20170206_1517'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=unload_data),
    ]
