# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0003_remove_song_on_playlist_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_on_playlist',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs_on_playlists', to='shakeitup.Song'),
        ),
    ]
