# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0003_auto_20170206_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_on_album',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_albums', to='shakeitup.Album'),
        ),
        migrations.AlterField(
            model_name='artist_on_album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_albums', to='shakeitup.Artist'),
        ),
    ]
