# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0008_auto_20170203_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_on_playlist',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shakeitup.Playlist'),
        ),
    ]
