# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0009_song_on_playlist_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_on_playlist',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='shakeitup.Playlist'),
        ),
        migrations.AlterField(
            model_name='song_on_playlist',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='shakeitup.Song'),
        ),
    ]
