# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0010_auto_20170203_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
