# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0011_auto_20170203_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('birth_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='collaborating_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='composing_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='songwriter_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shakeitup.Artist'),
        ),
    ]
