# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0012_auto_20170203_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_By_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres', to='shakeitup.Artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres', to='shakeitup.Genre')),
            ],
        ),
        migrations.AlterField(
            model_name='song_by_genre',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='shakeitup.Genre'),
        ),
        migrations.AlterField(
            model_name='song_by_genre',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='shakeitup.Song'),
        ),
    ]
