# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakeitup', '0014_album_album_by_genre_artist_on_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_On_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='shakeitup.Album')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='shakeitup.Song')),
            ],
        ),
    ]
