# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shakeitup', '0015_song_on_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
