# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shakeitup', '0017_auto_20170203_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_By_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AddField(
            model_name='playlist_by_user',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to='shakeitup.Playlist'),
        ),
        migrations.AddField(
            model_name='playlist_by_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
